:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

= MOAMOA

[[Auth]]
== 인증

=== Github 로그인
operation::auth/login[snippets='http-request,request-parameters,http-response,response-fields']

[[Member]]
== 회원

=== 스터디에서 나의 Role 확인
operation::members/me/role[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 로그인한 사용자 정보 조회
operation::members/me[snippets='http-request,request-headers,http-response']

[[Study]]
== 스터디

=== 스터디 생성
operation::studies/create[snippets='http-request,request-headers,http-response']

=== 스터디 참여
operation::studies/participant[snippets='http-request,http-response']

=== 스터디 목록 조회
operation::studies/summary[snippets='http-request,http-response']

=== 스터디 제목 검색
operation::studies/search[snippets='http-request,http-response']

=== 스터디 제목 검색 (필터링)
operation::studies/searchWithTags[snippets='http-request,http-response']

=== 스터디 세부 페이지
operation::studies/details[snippets='http-request,http-response']

=== 참여한 스터디 목록 조회
operation::studies/myStudy[snippets='http-request,http-response']

=== 스터디 상세 정보 수정
operation::studies/update[snippets='http-request,http-response']

=== 스터디 탈퇴
operation::studies/leave[snippets='http-request,request-headers,http-response']

[[Comunity]]
== 커뮤니티

=== 커뮤니티 생성
operation::article/create[snippets='http-request,request-headers,request-fields,http-response']

=== 커뮤니티 단건 조회
operation::article/get[snippets='http-request,request-headers,http-response,response-fields']

=== 커뮤니티 전체 조회
operation::article/list[snippets='http-request,request-headers,http-response,response-fields']

=== 커뮤니티 수정
operation::article/update[snippets='http-request,request-headers,http-response']

=== 커뮤니티 삭제
operation::article/delete[snippets='http-request,request-headers,http-response']

[[Notice]]
== 공지 게시글
=== 공지 생성
operation::write/notice[snippets='http-request,request-headers,request-fields,http-response']

=== 공지 단건 조회
operation::get/notice[snippets='http-request,request-headers,http-response,response-fields']

=== 공지 전체 조회
operation::get/notices[snippets='http-request,request-headers,http-response,response-fields']

=== 공지 수정
operation::update/notice[snippets='http-request,request-headers,http-response']

=== 공지 삭제
operation::delete/notice[snippets='http-request,request-headers,http-response']

[[Temp-Article]]
== 임시글

=== 임시글 생성
operation::temp-article/create[snippets='curl-request,http-request,http-response,path-parameters,request-fields,request-headers']

=== 임시글 단건 조회
operation::temp-article/get[snippets='curl-request,http-request,http-response,path-parameters,response-fields']

=== 임시글 전체 조회
operation::temp-articles/create[snippets='curl-request,http-request,http-response,path-parameters,response-fields']

=== 임시글 수정
operation::temp-article/update[snippets='curl-request,http-request,http-response,path-parameters,request-fields,request-headers']

=== 임시글 삭제
operation::temp-article/delete[snippets='curl-request,http-request,http-response,path-parameters']

[[Reference-Room]]
== 링크 공유

=== 링크 공유글 생성
operation::reference-room/create[snippets='http-request,request-headers,request-fields,http-response']

=== 링크 공유글 전체 조회
operation::reference-room/list[snippets='http-request,request-headers,http-response,response-fields']

=== 링크 공유글 수정
operation::reference-room/update[snippets='http-request,request-headers,http-response']

=== 링크 공유글 삭제
operation::reference-room/delete[snippets='http-request,request-headers,http-response']

[[Tag]]
== 태그

=== 태그 목록 조회
operation::tags/list[snippets='http-request,http-response']

=== 태그 목록 검색
operation::tags/search[snippets='http-request,http-response']

[[Review]]
== 스터디 후기

=== 후기 작성
operation::reviews/create[snippets='http-request,http-response']

=== 후기 전체 조회
operation::reviews/list[snippets='http-request,http-response']

=== 후기 특정 개수 조회
operation::reviews/list-certain-number[snippets='http-request,http-response']

=== 리뷰 수정
operation::reviews/update[snippets='http-request,http-response']

=== 리뷰 삭제
operation::reviews/delete[snippets='http-request,http-response']

[[Comments]]
== 게시글 댓글

=== 댓글 작성
operation::comments/create[snippets='http-request,http-response']

=== 댓글 전체 조회
operation::comments/list[snippets='http-request,http-response']

=== 댓글 수정
operation::comments/update[snippets='http-request,http-response']

=== 댓글 삭제
operation::comments/delete[snippets='http-request,http-response']
