import { Story } from '@storybook/react';

import Wrapper from '@components/wrapper/Wrapper';

import MyStudyCardListSection from '@my-study-page/components/my-study-card-list-section/MyStudyCardListSection';
import type { MyStudyCardListSectionProps } from '@my-study-page/components/my-study-card-list-section/MyStudyCardListSection';

export default {
  title: 'Components/MyStudyCardListSection',
  component: MyStudyCardListSection,
  argTypes: {
    sectionTitle: { controls: 'text' },
    myStudies: { controls: 'object' },
  },
};

const Template: Story<MyStudyCardListSectionProps> = props => (
  <Wrapper>
    <MyStudyCardListSection {...props} />
  </Wrapper>
);

export const Default = Template.bind({});
Default.args = {
  sectionTitle: '활동 중!',
  myStudies: [
    {
      id: 53172832,
      title: '2022-daily-planner',
      studyStatus: 'IN_PROGRESS',
      startDate: '2022-07-12',
      endDate: '2022-08-18',
      owner: {
        id: 19749913,
        username: 'xRC3N',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
      ],
    },
    {
      id: 74198334,
      title: '2022-lv3-algorithm-study',
      studyStatus: 'IN_PROGRESS',
      startDate: '2022-07-24',
      endDate: '2022-08-08',
      owner: {
        id: 73846379,
        username: 'i8ZTZ',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
        { id: 9, name: 'Book' },
        { id: 10, name: 'Health' },
        { id: 11, name: 'Network' },
        { id: 12, name: 'CS' },
      ],
    },
    {
      id: 43942846,
      title: '2022-woowahan-bansanghwe',
      studyStatus: 'PREPARE',
      startDate: '2022-07-20',
      endDate: '2022-08-31',
      owner: {
        id: 82157345,
        username: 'QtbTJ',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
        { id: 9, name: 'Book' },
      ],
    },
    {
      id: 19264566,
      title: '2022-gugu-spring-study',
      studyStatus: 'PREPARE',
      startDate: '2022-07-05',
      endDate: '2022-08-27',
      owner: {
        id: 73501209,
        username: 'xE5Gh',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
      ],
    },
    {
      id: 26808604,
      title: '2022-ConquerCS',
      studyStatus: 'DONE',
      startDate: '2022-07-25',
      endDate: '2022-08-18',
      owner: {
        id: 19148355,
        username: '-LBJx',
      },
      tags: [{ id: 1, name: 'JS' }],
    },
    {
      id: 36977774,
      title: '2022-looking-for-the-sound-of-an-object',
      studyStatus: 'IN_PROGRESS',
      startDate: '2022-07-11',
      endDate: '2022-08-22',
      owner: {
        id: 61097544,
        username: '50a_j',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
        { id: 9, name: 'Book' },
        { id: 10, name: 'Health' },
      ],
    },
    {
      id: 28043313,
      title: '2022-kotudy',
      studyStatus: 'DONE',
      startDate: '2022-07-24',
      endDate: '2022-08-20',
      owner: {
        id: 47838157,
        username: '-02j_',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
        { id: 9, name: 'Book' },
      ],
    },
    {
      id: 92951646,
      title: '2022-no-posting-you-die',
      studyStatus: 'DONE',
      startDate: '2022-07-03',
      endDate: '2022-08-11',
      owner: {
        id: 74007869,
        username: 'dCMAR',
      },
      tags: [{ id: 1, name: 'JS' }],
    },
    {
      id: 27364158,
      title: '2022-Real-MySQL',
      studyStatus: 'DONE',
      startDate: '2022-07-25',
      endDate: '2022-08-02',
      owner: {
        id: 13018728,
        username: 'pmnMx',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
        { id: 9, name: 'Book' },
        { id: 10, name: 'Health' },
        { id: 11, name: 'Network' },
      ],
    },
    {
      id: 87571081,
      title: '2022-weekly-log',
      studyStatus: 'DONE',
      startDate: '2022-07-04',
      endDate: '2022-08-26',
      owner: {
        id: 43897221,
        username: 'cCcfy',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
        { id: 9, name: 'Book' },
        { id: 10, name: 'Health' },
        { id: 11, name: 'Network' },
        { id: 12, name: 'CS' },
      ],
    },
    {
      id: 48700521,
      title: '2022-spring-study',
      studyStatus: 'DONE',
      startDate: '2022-07-25',
      endDate: '2022-08-06',
      owner: {
        id: 56121153,
        username: '-ShmC',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
      ],
    },
    {
      id: 37351958,
      title: 'http-network-basic-level2-study',
      studyStatus: 'DONE',
      startDate: '2022-07-17',
      endDate: '2022-08-26',
      owner: {
        id: 64342856,
        username: 'udN0b',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
      ],
    },
    {
      id: 47071629,
      title: '2022-code-review-study-2',
      studyStatus: 'PREPARE',
      startDate: '2022-07-06',
      endDate: '2022-08-29',
      owner: {
        id: 16398644,
        username: '8yC-b',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
        { id: 9, name: 'Book' },
        { id: 10, name: 'Health' },
      ],
    },
    {
      id: 11340744,
      title: '2022-http-web-basic-for-all-developer',
      studyStatus: 'IN_PROGRESS',
      startDate: '2022-07-07',
      endDate: '2022-08-19',
      owner: {
        id: 17465872,
        username: 'qNknz',
      },
      tags: [{ id: 1, name: 'JS' }],
    },
    {
      id: 37178275,
      title: '2022-woowa-retrospect',
      studyStatus: 'DONE',
      startDate: '2022-07-05',
      endDate: '2022-08-11',
      owner: {
        id: 82056531,
        username: 'XGbcR',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
        { id: 9, name: 'Book' },
      ],
    },
    {
      id: 20176840,
      title: '2022-http-network-basic-study',
      studyStatus: 'DONE',
      startDate: '2022-07-05',
      endDate: '2022-08-30',
      owner: {
        id: 68132562,
        username: 'M9MbV',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
      ],
    },
    {
      id: 88252874,
      title: '2022-lv2-effective-java-interview',
      studyStatus: 'DONE',
      startDate: '2022-07-28',
      endDate: '2022-08-06',
      owner: {
        id: 76714791,
        username: 'kHuuu',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
        { id: 9, name: 'Book' },
        { id: 10, name: 'Health' },
        { id: 11, name: 'Network' },
      ],
    },
    {
      id: 35867370,
      title: '2022-book-muscle',
      studyStatus: 'DONE',
      startDate: '2022-07-29',
      endDate: '2022-08-06',
      owner: {
        id: 75253381,
        username: 'N-7qD',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
        { id: 9, name: 'Book' },
        { id: 10, name: 'Health' },
        { id: 11, name: 'Network' },
      ],
    },
    {
      id: 95367364,
      title: '2022-woowahan-everybook',
      studyStatus: 'PREPARE',
      startDate: '2022-07-29',
      endDate: '2022-08-04',
      owner: {
        id: 98385754,
        username: 'GwfDt',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
      ],
    },
  ],
};
