import { type Story } from '@storybook/react';

import Wrapper from '@components/wrapper/Wrapper';

import MyStudyCardListSection, {
  type MyStudyCardListSectionProps,
} from '@my-study-page/components/my-study-card-list-section/MyStudyCardListSection';

export default {
  title: 'Pages/MyStudyPage/MyStudyCardListSection',
  component: MyStudyCardListSection,
};

const Template: Story<MyStudyCardListSectionProps> = props => (
  <Wrapper>
    <MyStudyCardListSection {...props} />
  </Wrapper>
);

export const Default = Template.bind({});
Default.args = {
  done: false,
  sectionTitle: '활동 중!',
  studies: [
    {
      id: 66201614,
      title: '2022-daily-planner',
      studyStatus: 'IN_PROGRESS',
      startDate: '2022-07-23',
      endDate: '2022-08-15',
      owner: {
        id: 92896738,
        username: 'tlrwu',
        imageUrl: 'https://picsum.photos/id/28/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
        { id: 9, name: 'Book' },
      ],
    },
    {
      id: 48145504,
      title: '2022-lv3-algorithm-study',
      studyStatus: 'IN_PROGRESS',
      startDate: '2022-07-17',
      endDate: '2022-08-10',
      owner: {
        id: 21510457,
        username: 'q_Ykn',
        imageUrl: 'https://picsum.photos/id/81/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
      ],
    },
    {
      id: 97061298,
      title: '2022-woowahan-bansanghwe',
      studyStatus: 'DONE',
      startDate: '2022-07-06',
      endDate: '2022-08-10',
      owner: {
        id: 43538679,
        username: 'qxZGs',
        imageUrl: 'https://picsum.photos/id/40/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
      ],
    },
    {
      id: 49435359,
      title: '2022-gugu-spring-study',
      studyStatus: 'PREPARE',
      startDate: '2022-07-01',
      endDate: '2022-08-15',
      owner: {
        id: 60385572,
        username: '9Zw76',
        imageUrl: 'https://picsum.photos/id/91/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
      ],
    },
    {
      id: 16574939,
      title: '2022-ConquerCS',
      studyStatus: 'DONE',
      startDate: '2022-07-05',
      endDate: '2022-08-21',
      owner: {
        id: 23354134,
        username: '02tHi',
        imageUrl: 'https://picsum.photos/id/28/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
      ],
    },
    {
      id: 96544840,
      title: '2022-looking-for-the-sound-of-an-object',
      studyStatus: 'DONE',
      startDate: '2022-07-08',
      endDate: '2022-08-09',
      owner: {
        id: 16177752,
        username: 'SYxJj',
        imageUrl: 'https://picsum.photos/id/24/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
      ],
    },
    {
      id: 46933900,
      title: '2022-kotudy',
      studyStatus: 'DONE',
      startDate: '2022-07-18',
      endDate: '2022-08-15',
      owner: {
        id: 24136661,
        username: 'Cj0XW',
        imageUrl: 'https://picsum.photos/id/65/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
      ],
    },
    {
      id: 15671727,
      title: '2022-no-posting-you-die',
      studyStatus: 'IN_PROGRESS',
      startDate: '2022-07-11',
      endDate: '2022-08-09',
      owner: {
        id: 96860992,
        username: 'IDq7d',
        imageUrl: 'https://picsum.photos/id/67/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
        { id: 9, name: 'Book' },
        { id: 10, name: 'Health' },
        { id: 11, name: 'Network' },
      ],
    },
    {
      id: 23314301,
      title: '2022-Real-MySQL',
      studyStatus: 'DONE',
      startDate: '2022-07-28',
      endDate: '2022-08-02',
      owner: {
        id: 11138773,
        username: 'zEKTW',
        imageUrl: 'https://picsum.photos/id/80/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
      ],
    },
    {
      id: 55674066,
      title: '2022-weekly-log',
      studyStatus: 'DONE',
      startDate: '2022-07-14',
      endDate: '2022-08-07',
      owner: {
        id: 82512601,
        username: '1SOyb',
        imageUrl: 'https://picsum.photos/id/35/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [{ id: 1, name: 'JS' }],
    },
    {
      id: 83602317,
      title: '2022-spring-study',
      studyStatus: 'PREPARE',
      startDate: '2022-07-21',
      endDate: '2022-08-18',
      owner: {
        id: 83123314,
        username: 'YMFbu',
        imageUrl: 'https://picsum.photos/id/75/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
      ],
    },
    {
      id: 203695,
      title: 'http-network-basic-level2-study',
      studyStatus: 'PREPARE',
      startDate: '2022-07-01',
      endDate: '2022-08-22',
      owner: {
        id: 29254663,
        username: 'cPMxd',
        imageUrl: 'https://picsum.photos/id/46/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
      ],
    },
    {
      id: 15132719,
      title: '2022-code-review-study-2',
      studyStatus: 'IN_PROGRESS',
      startDate: '2022-07-14',
      endDate: '2022-08-23',
      owner: {
        id: 54186432,
        username: '6PzoH',
        imageUrl: 'https://picsum.photos/id/92/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
        { id: 9, name: 'Book' },
        { id: 10, name: 'Health' },
      ],
    },
    {
      id: 94627904,
      title: '2022-http-web-basic-for-all-developer',
      studyStatus: 'IN_PROGRESS',
      startDate: '2022-07-14',
      endDate: '2022-08-08',
      owner: {
        id: 77175593,
        username: 'z6mBk',
        imageUrl: 'https://picsum.photos/id/8/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
      ],
    },
    {
      id: 36433985,
      title: '2022-woowa-retrospect',
      studyStatus: 'PREPARE',
      startDate: '2022-07-22',
      endDate: '2022-08-14',
      owner: {
        id: 71177024,
        username: 'qfUth',
        imageUrl: 'https://picsum.photos/id/57/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
      ],
    },
    {
      id: 17465610,
      title: '2022-http-network-basic-study',
      studyStatus: 'IN_PROGRESS',
      startDate: '2022-07-01',
      endDate: '2022-08-12',
      owner: {
        id: 27678301,
        username: 'n0mnb',
        imageUrl: 'https://picsum.photos/id/67/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
        { id: 9, name: 'Book' },
        { id: 10, name: 'Health' },
      ],
    },
    {
      id: 79836854,
      title: '2022-lv2-effective-java-interview',
      studyStatus: 'DONE',
      startDate: '2022-07-29',
      endDate: '2022-08-07',
      owner: {
        id: 8714542,
        username: '4vPR_',
        imageUrl: 'https://picsum.photos/id/60/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
      ],
    },
    {
      id: 74269566,
      title: '2022-book-muscle',
      studyStatus: 'PREPARE',
      startDate: '2022-07-19',
      endDate: '2022-08-26',
      owner: {
        id: 45039085,
        username: 'Uy4Fb',
        imageUrl: 'https://picsum.photos/id/51/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
        { id: 5, name: 'TS' },
        { id: 6, name: 'JPA' },
        { id: 7, name: 'TDD' },
        { id: 8, name: 'Alg' },
      ],
    },
    {
      id: 28669351,
      title: '2022-woowahan-everybook',
      studyStatus: 'DONE',
      startDate: '2022-07-17',
      endDate: '2022-08-05',
      owner: {
        id: 50208869,
        username: 'tl94j',
        imageUrl: 'https://picsum.photos/id/27/200/200',
        profileUrl: 'https://github.com/user/jaejae-yoo',
      },
      tags: [
        { id: 1, name: 'JS' },
        { id: 2, name: 'Java' },
        { id: 3, name: 'React' },
        { id: 4, name: 'Spring' },
      ],
    },
  ],
};
