spring:
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  profiles:
    include: security
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: 2022-moamoa-thumbnail
