name: moamoa-sonarqube
on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, '🖥 backend')
    defaults:
      run:
        working-directory: ./backend
    env:
      SONARQUBE_PROJECT_KEY: moamoa
      SONARQUBE_URL: ${{ secrets.SONAR_HOST_URL }}
      SONARQUBE_TOKEN : ${{ secrets.SONAR_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      client-id: ${{ secrets.CLIENT_ID }}
      client-secret: ${{ secrets.CLIENT_SECRET }}
      jwt-secret-key: ${{ secrets.JWT_SECRET_KEY }}
      jwt-expire-length: ${{ secrets.JWT_EXPIRE_LENGTH }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: gradlew permission change
        run: sudo chmod 755 gradlew
        
      - name: Sonaqube Analysis        
        run: ./gradlew build sonarqube
             -Dsonar.host.url=${{ env.SONAR_HOST_URL }}
             -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
             -Dsonar.projectName=${{ env.SONAR_PROJECT_KEY }}-${{ env.PR_NUMBER }}
             -Dsonar.login=${{ env.SONAR_TOKEN }}
             -Doauth2.github.client-id=${{ env.client-id }} 
             -Doauth2.github.client-secret=${{ env.client-secret }} 
             -Dsecurity.jwt.token.secret-key=${{ env.jwt-secret-key }} 
             -Dsecurity.jwt.token.expire-length=${{ env.jwt-expire-length }}
           
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
